### PR TITLE
fix: Pod install issue & listener conflict with document picker library

### PR DESCRIPTION
**Pull request by rinku-k**
The pull request contains below fix - 
1. Pod demo swift added - helps users to run 'pod install' inside **the library** directly
https://github.com/prscX/react-native-file-selector/issues/23

2. Conflict with listener
File-selector plugin is listening to document-picker file selection and throwing error causing app crash in some mobiles.

### CODE REVIEW

**Comment by prscX** [comment]
Thanks @Rinkuk1993 for the Effort and PR.

- w.r.t first point: the fix is for pod installation? Could you please share the exception which you were getting.

- second point: fix w.r.t conflict with listener looks good.

Thanks
</ Pranav >

**Comment by Rinkuk1993** [comment]
For the first point -
You can check this thread https://github.com/prscX/react-native-file-selector/issues/23
https://github.com/prscX/react-native-file-selector/issues/28

Normally people are not able to do `pod install` inside the library due to unavailability of swift file. 
They have to manually create one from Xcode(normally people don't know how to do it).
**For reference** - check my comment on the issue thread.

This fix will simply remove unwanted confusion.

Thanks

**Comment by Rinkuk1993** [comment]
Is there an issue merging the changes? I am not sure about the status of this PR since there is no response

**Comment by crutchcorn** [comment]
I get the following error for this PR for iOS usage:

```
[!] The `RNFileSelector` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.
```

**Comment by crutchcorn** [comment]
All it took to solve this issue was to change the podspec file:
```
  s.homepage     = "https://github.com/prscX/react-native-file-selector"
```

**Comment by rinku-k** [comment]
> Conflict with listener
> File-selector plugin is listening to document-picker file selection and throwing error causing app crash in some mobiles.

I see that someone has already added PR for the above fix due to my inactivity. Since the code is same, I have removed my code.

> Pod demo swift added - helps users to run 'pod install' inside the library directly
> #23

If the issue "Pod demo swift added" is also fixed, let's close this PR.

**Pull request closed without merging**
